### ISSUE TITLE
postgres container fails to start with POSTGRES_PASSWORD_FILE defined

### ISSUE THREAD

**Issue by frebib** [immich-app/base-images#229]
As per the 133 release announcement, I switched to using the immich-provided image. My compose definition is as follows:
```
  db:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_USER: immich
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_INITDB_ARGS: '--data-checksums'
    secrets:
      - db-password
    volumes:
      - ./database:/var/lib/postgresql/data
      - &postgres-sockets
        type: volume
        source: postgres-sockets
        target: /var/run/postgresql
        volume:
          nocopy: true
    network_mode: none
    restart: on-failure
```

This is how I had it set up previously, ignoring the image name difference.
It seems to me like the init script that loads the password from file is probably interfering with postgres loading these passwords itself?
